# Generated by Django 6.0.6 on 2026-06-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_station_latitude_alter_station_longitude_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cargo_num', models.PositiveIntegerField()),
                ('places_in_cargo', models.PositiveIntegerField()),
                ('train_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='station.traintype')),
            ],
        ),
    ]
